-- Triavia schema — PostgreSQL flavour (same tables, same meaning as the SQLite file).

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider      TEXT NOT NULL,
    provider_id   TEXT NOT NULL,
    name          TEXT,
    email         TEXT,
    phone         TEXT,
    created_at    TEXT NOT NULL,
    last_login_at TEXT,
    UNIQUE (provider, provider_id)
);

CREATE TABLE IF NOT EXISTS assessments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    created_at      TEXT    NOT NULL,
    age             INTEGER NOT NULL,
    chief_complaint TEXT    NOT NULL,
    triage_level    INTEGER NOT NULL CHECK (triage_level BETWEEN 0 AND 3),
    triage_label    TEXT    NOT NULL,
    confidence      DOUBLE PRECISION NOT NULL,
    safety_override INTEGER NOT NULL DEFAULT 0,
    inputs_json     TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_assessments_created ON assessments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_assessments_user ON assessments(user_id, id DESC);

CREATE TABLE IF NOT EXISTS otp_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone      TEXT NOT NULL,
    code_hash  TEXT NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    attempts   INTEGER NOT NULL DEFAULT 0,
    created_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_otp_phone ON otp_codes(phone, created_at);

CREATE TABLE IF NOT EXISTS login_codes (
    code_hash  TEXT PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
);

-- Visitor feedback from the in-app form (read by the author via GET /api/v1/feedback with the service key)
CREATE TABLE IF NOT EXISTS feedback (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT NOT NULL,
    user_id    BIGINT,
    rating     INTEGER,
    message    TEXT NOT NULL,
    contact    TEXT
);
